name: Publish to DockerHub

on:
  push:
    branches:
      - main

jobs:
  docker-build:
    runs-on: depot-ubuntu-22.04
    name: Docker Build
    permissions:
      contents: read
      id-token: write
      actions: read
      packages: write
    environment: dockerhub
    steps:
      - uses: actions/checkout@v4

      - uses: depot/setup-action@v1
        with:
          oidc: true

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: insecureapps/broken-flask
          tags: |
            type=raw,value=latest,enable=true

      - name: Build and Push Docker Images to DockerHub
        uses: depot/build-push-action@v1
        with:
          project: 3tk5v5p8nq
          context: ./
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
